//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "InstituteBuildingCard")]
        public string WebServices_InstituteReference_InstituteBuildingCard_Service {
            get {
                return ((string)(this["WebServices_InstituteReference_InstituteBuildingCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "HostelBuildingCard")]
        public string WebServices_HostelReference_HostelBuildingCard_Service {
            get {
                return ((string)(this["WebServices_HostelReference_HostelBuildingCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "StaffQuarterCard")]
        public string WebServices_StaffReference_StaffQuarterCard_Service {
            get {
                return ((string)(this["WebServices_StaffReference_StaffQuarterCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "AuditoriumBuilding")]
        public string WebServices_AuditoriumReference_AuditoriumBuilding_Service {
            get {
                return ((string)(this["WebServices_AuditoriumReference_AuditoriumBuilding_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "Newprojectcard")]
        public string WebServices_NewProjectReference_Newprojectcard_Service {
            get {
                return ((string)(this["WebServices_NewProjectReference_Newprojectcard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "Improvementprojectcard")]
        public string WebServices_ImprovementProjectReference_Improvementprojectcard_Service {
            get {
                return ((string)(this["WebServices_ImprovementProjectReference_Improvementprojectcard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "Ongoingprojectcard")]
        public string WebServices_OngoingProjectReference_Ongoingprojectcard_Service {
            get {
                return ((string)(this["WebServices_OngoingProjectReference_Ongoingprojectcard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "Projectprogressdetailscard")]
        public string WebServices_ProjectProgressReference_Projectprogressdetailscard_Service {
            get {
                return ((string)(this["WebServices_ProjectProgressReference_Projectprogressdetailscard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "EstimatePrepCard")]
        public string WebServices_EstimatePrepReference_EstimatePrepCard_Service {
            get {
                return ((string)(this["WebServices_EstimatePrepReference_EstimatePrepCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "ServiceCard")]
        public string WebServices_ServiceCardReference_ServiceCard_Service {
            get {
                return ((string)(this["WebServices_ServiceCardReference_ServiceCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "AMCCard")]
        public string WebServices_AMCCardReference_AMCCard_Service {
            get {
                return ((string)(this["WebServices_AMCCardReference_AMCCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "LandCard")]
        public string WebServices_LandReference_LandCard_Service {
            get {
                return ((string)(this["WebServices_LandReference_LandCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Page/" +
            "GeneralLandBuildingCard")]
        public string WebServices_GeneralLandBuildingReference_GeneralLandBuildingCard_Service {
            get {
                return ((string)(this["WebServices_GeneralLandBuildingReference_GeneralLandBuildingCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://genesisnav16.atlas.betpilani.org:8047/BC200/WS/CRONUS%20India%20Ltd./Codeu" +
            "nit/InfraCodeunit")]
        public string WebServices_CodeUnitReference_InfraCodeunit {
            get {
                return ((string)(this["WebServices_CodeUnitReference_InfraCodeunit"]));
            }
        }
    }
}
