//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebServices.GeneralLandBuildingReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeneralLandBuildingCard_Binding", Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public partial class GeneralLandBuildingCard_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GeneralLandBuildingCard_Service() {
            this.Url = global::WebServices.Properties.Settings.Default.WebServices_GeneralLandBuildingReference_GeneralLandBuildingCard_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generallandbuildingcard:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GeneralLandBuildingCard")]
        public GeneralLandBuildingCard ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((GeneralLandBuildingCard)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generallandbuildingcard:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GeneralLandBuildingCard[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] GeneralLandBuildingCard_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((GeneralLandBuildingCard[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(GeneralLandBuildingCard_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(GeneralLandBuildingCard_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generallandbuildingcard:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generallandbuildingcard:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generallandbuildingcard:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref GeneralLandBuildingCard GeneralLandBuildingCard) {
            object[] results = this.Invoke("Create", new object[] {
                        GeneralLandBuildingCard});
            GeneralLandBuildingCard = ((GeneralLandBuildingCard)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(GeneralLandBuildingCard GeneralLandBuildingCard) {
            this.CreateAsync(GeneralLandBuildingCard, null);
        }
        
        /// <remarks/>
        public void CreateAsync(GeneralLandBuildingCard GeneralLandBuildingCard, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        GeneralLandBuildingCard}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generallandbuildingcard:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref GeneralLandBuildingCard[] GeneralLandBuildingCard_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        GeneralLandBuildingCard_List});
            GeneralLandBuildingCard_List = ((GeneralLandBuildingCard[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(GeneralLandBuildingCard[] GeneralLandBuildingCard_List) {
            this.CreateMultipleAsync(GeneralLandBuildingCard_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(GeneralLandBuildingCard[] GeneralLandBuildingCard_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        GeneralLandBuildingCard_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generallandbuildingcard:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref GeneralLandBuildingCard GeneralLandBuildingCard) {
            object[] results = this.Invoke("Update", new object[] {
                        GeneralLandBuildingCard});
            GeneralLandBuildingCard = ((GeneralLandBuildingCard)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(GeneralLandBuildingCard GeneralLandBuildingCard) {
            this.UpdateAsync(GeneralLandBuildingCard, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(GeneralLandBuildingCard GeneralLandBuildingCard, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        GeneralLandBuildingCard}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/generallandbuildingcard:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref GeneralLandBuildingCard[] GeneralLandBuildingCard_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        GeneralLandBuildingCard_List});
            GeneralLandBuildingCard_List = ((GeneralLandBuildingCard[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(GeneralLandBuildingCard[] GeneralLandBuildingCard_List) {
            this.UpdateMultipleAsync(GeneralLandBuildingCard_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(GeneralLandBuildingCard[] GeneralLandBuildingCard_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        GeneralLandBuildingCard_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public partial class GeneralLandBuildingCard {
        
        private string keyField;
        
        private string year_of_Establis_of_instituteField;
        
        private Field_Available field_AvailableField;
        
        private bool field_AvailableFieldSpecified;
        
        private decimal field_Area_in_AcresField;
        
        private bool field_Area_in_AcresFieldSpecified;
        
        private Sports_Court_Available sports_Court_AvailableField;
        
        private bool sports_Court_AvailableFieldSpecified;
        
        private decimal sports_Court_Area_in_SqftField;
        
        private bool sports_Court_Area_in_SqftFieldSpecified;
        
        private Field_Gallery_Available field_Gallery_AvailableField;
        
        private bool field_Gallery_AvailableFieldSpecified;
        
        private Conference_Room_Available conference_Room_AvailableField;
        
        private bool conference_Room_AvailableFieldSpecified;
        
        private Video_Conference_Room_Avail video_Conference_Room_AvailField;
        
        private bool video_Conference_Room_AvailFieldSpecified;
        
        private decimal floor_size_of_the_Video_confField;
        
        private bool floor_size_of_the_Video_confFieldSpecified;
        
        private string video_Conference_Room_LocationField;
        
        private int video_Conference_Room_CapacityField;
        
        private bool video_Conference_Room_CapacityFieldSpecified;
        
        private Library_Available library_AvailableField;
        
        private bool library_AvailableFieldSpecified;
        
        private Central_Library_Available central_Library_AvailableField;
        
        private bool central_Library_AvailableFieldSpecified;
        
        private Digital_Library_Available digital_Library_AvailableField;
        
        private bool digital_Library_AvailableFieldSpecified;
        
        private Canteen_Caf_for_Staffs_Avail canteen_Caf_for_Staffs_AvailField;
        
        private bool canteen_Caf_for_Staffs_AvailFieldSpecified;
        
        private int canteen_Cafeteria_CapacityField;
        
        private bool canteen_Cafeteria_CapacityFieldSpecified;
        
        private Dispensary_Available dispensary_AvailableField;
        
        private bool dispensary_AvailableFieldSpecified;
        
        private CoE_Program_Available coE_Program_AvailableField;
        
        private bool coE_Program_AvailableFieldSpecified;
        
        private string coE_Program_DetailsField;
        
        private CSR_Activities_Available cSR_Activities_AvailableField;
        
        private bool cSR_Activities_AvailableFieldSpecified;
        
        private string cSR_Activity_DetailsField;
        
        private Staff_Common_Room_Available staff_Common_Room_AvailableField;
        
        private bool staff_Common_Room_AvailableFieldSpecified;
        
        private string staff_Common_Room_DetailsField;
        
        private Girls_Common_Room_Available girls_Common_Room_AvailableField;
        
        private bool girls_Common_Room_AvailableFieldSpecified;
        
        private string girls_Common_Room_DetailsField;
        
        private Boys_Common_Room_Available boys_Common_Room_AvailableField;
        
        private bool boys_Common_Room_AvailableFieldSpecified;
        
        private string boys_Common_Room_DetailsField;
        
        private Roof_Top_Solar_Panel_Available roof_Top_Solar_Panel_AvailableField;
        
        private bool roof_Top_Solar_Panel_AvailableFieldSpecified;
        
        private Rain_Water_Harvesting_Avail rain_Water_Harvesting_AvailField;
        
        private bool rain_Water_Harvesting_AvailFieldSpecified;
        
        private Sewage_Treatment_Plant_Avail sewage_Treatment_Plant_AvailField;
        
        private bool sewage_Treatment_Plant_AvailFieldSpecified;
        
        private Internet_Connection_Available internet_Connection_AvailableField;
        
        private bool internet_Connection_AvailableFieldSpecified;
        
        private string uploaded_FileNameField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Year_of_Establis_of_institute {
            get {
                return this.year_of_Establis_of_instituteField;
            }
            set {
                this.year_of_Establis_of_instituteField = value;
            }
        }
        
        /// <remarks/>
        public Field_Available Field_Available {
            get {
                return this.field_AvailableField;
            }
            set {
                this.field_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Field_AvailableSpecified {
            get {
                return this.field_AvailableFieldSpecified;
            }
            set {
                this.field_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Field_Area_in_Acres {
            get {
                return this.field_Area_in_AcresField;
            }
            set {
                this.field_Area_in_AcresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Field_Area_in_AcresSpecified {
            get {
                return this.field_Area_in_AcresFieldSpecified;
            }
            set {
                this.field_Area_in_AcresFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sport’s_Court_Available")]
        public Sports_Court_Available Sports_Court_Available {
            get {
                return this.sports_Court_AvailableField;
            }
            set {
                this.sports_Court_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sports_Court_AvailableSpecified {
            get {
                return this.sports_Court_AvailableFieldSpecified;
            }
            set {
                this.sports_Court_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Sports_Court_Area_in_Sqft {
            get {
                return this.sports_Court_Area_in_SqftField;
            }
            set {
                this.sports_Court_Area_in_SqftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sports_Court_Area_in_SqftSpecified {
            get {
                return this.sports_Court_Area_in_SqftFieldSpecified;
            }
            set {
                this.sports_Court_Area_in_SqftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Field_Gallery_Available Field_Gallery_Available {
            get {
                return this.field_Gallery_AvailableField;
            }
            set {
                this.field_Gallery_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Field_Gallery_AvailableSpecified {
            get {
                return this.field_Gallery_AvailableFieldSpecified;
            }
            set {
                this.field_Gallery_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Conference_Room_Available Conference_Room_Available {
            get {
                return this.conference_Room_AvailableField;
            }
            set {
                this.conference_Room_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Conference_Room_AvailableSpecified {
            get {
                return this.conference_Room_AvailableFieldSpecified;
            }
            set {
                this.conference_Room_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Video_Conference_Room_Avail Video_Conference_Room_Avail {
            get {
                return this.video_Conference_Room_AvailField;
            }
            set {
                this.video_Conference_Room_AvailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Video_Conference_Room_AvailSpecified {
            get {
                return this.video_Conference_Room_AvailFieldSpecified;
            }
            set {
                this.video_Conference_Room_AvailFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Floor_size_of_the_Video_conf {
            get {
                return this.floor_size_of_the_Video_confField;
            }
            set {
                this.floor_size_of_the_Video_confField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Floor_size_of_the_Video_confSpecified {
            get {
                return this.floor_size_of_the_Video_confFieldSpecified;
            }
            set {
                this.floor_size_of_the_Video_confFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Video_Conference_Room_Location {
            get {
                return this.video_Conference_Room_LocationField;
            }
            set {
                this.video_Conference_Room_LocationField = value;
            }
        }
        
        /// <remarks/>
        public int Video_Conference_Room_Capacity {
            get {
                return this.video_Conference_Room_CapacityField;
            }
            set {
                this.video_Conference_Room_CapacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Video_Conference_Room_CapacitySpecified {
            get {
                return this.video_Conference_Room_CapacityFieldSpecified;
            }
            set {
                this.video_Conference_Room_CapacityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Library_Available Library_Available {
            get {
                return this.library_AvailableField;
            }
            set {
                this.library_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Library_AvailableSpecified {
            get {
                return this.library_AvailableFieldSpecified;
            }
            set {
                this.library_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Central_Library_Available Central_Library_Available {
            get {
                return this.central_Library_AvailableField;
            }
            set {
                this.central_Library_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Central_Library_AvailableSpecified {
            get {
                return this.central_Library_AvailableFieldSpecified;
            }
            set {
                this.central_Library_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Digital_Library_Available Digital_Library_Available {
            get {
                return this.digital_Library_AvailableField;
            }
            set {
                this.digital_Library_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Digital_Library_AvailableSpecified {
            get {
                return this.digital_Library_AvailableFieldSpecified;
            }
            set {
                this.digital_Library_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Canteen_Caf_for_Staffs_Avail Canteen_Caf_for_Staffs_Avail {
            get {
                return this.canteen_Caf_for_Staffs_AvailField;
            }
            set {
                this.canteen_Caf_for_Staffs_AvailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Canteen_Caf_for_Staffs_AvailSpecified {
            get {
                return this.canteen_Caf_for_Staffs_AvailFieldSpecified;
            }
            set {
                this.canteen_Caf_for_Staffs_AvailFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Canteen_Cafeteria_Capacity {
            get {
                return this.canteen_Cafeteria_CapacityField;
            }
            set {
                this.canteen_Cafeteria_CapacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Canteen_Cafeteria_CapacitySpecified {
            get {
                return this.canteen_Cafeteria_CapacityFieldSpecified;
            }
            set {
                this.canteen_Cafeteria_CapacityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Dispensary_Available Dispensary_Available {
            get {
                return this.dispensary_AvailableField;
            }
            set {
                this.dispensary_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Dispensary_AvailableSpecified {
            get {
                return this.dispensary_AvailableFieldSpecified;
            }
            set {
                this.dispensary_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CoE_Program_Available CoE_Program_Available {
            get {
                return this.coE_Program_AvailableField;
            }
            set {
                this.coE_Program_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoE_Program_AvailableSpecified {
            get {
                return this.coE_Program_AvailableFieldSpecified;
            }
            set {
                this.coE_Program_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CoE_Program_Details {
            get {
                return this.coE_Program_DetailsField;
            }
            set {
                this.coE_Program_DetailsField = value;
            }
        }
        
        /// <remarks/>
        public CSR_Activities_Available CSR_Activities_Available {
            get {
                return this.cSR_Activities_AvailableField;
            }
            set {
                this.cSR_Activities_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CSR_Activities_AvailableSpecified {
            get {
                return this.cSR_Activities_AvailableFieldSpecified;
            }
            set {
                this.cSR_Activities_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CSR_Activity_Details {
            get {
                return this.cSR_Activity_DetailsField;
            }
            set {
                this.cSR_Activity_DetailsField = value;
            }
        }
        
        /// <remarks/>
        public Staff_Common_Room_Available Staff_Common_Room_Available {
            get {
                return this.staff_Common_Room_AvailableField;
            }
            set {
                this.staff_Common_Room_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Staff_Common_Room_AvailableSpecified {
            get {
                return this.staff_Common_Room_AvailableFieldSpecified;
            }
            set {
                this.staff_Common_Room_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Staff_Common_Room_Details {
            get {
                return this.staff_Common_Room_DetailsField;
            }
            set {
                this.staff_Common_Room_DetailsField = value;
            }
        }
        
        /// <remarks/>
        public Girls_Common_Room_Available Girls_Common_Room_Available {
            get {
                return this.girls_Common_Room_AvailableField;
            }
            set {
                this.girls_Common_Room_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Girls_Common_Room_AvailableSpecified {
            get {
                return this.girls_Common_Room_AvailableFieldSpecified;
            }
            set {
                this.girls_Common_Room_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Girls_Common_Room_Details {
            get {
                return this.girls_Common_Room_DetailsField;
            }
            set {
                this.girls_Common_Room_DetailsField = value;
            }
        }
        
        /// <remarks/>
        public Boys_Common_Room_Available Boys_Common_Room_Available {
            get {
                return this.boys_Common_Room_AvailableField;
            }
            set {
                this.boys_Common_Room_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Boys_Common_Room_AvailableSpecified {
            get {
                return this.boys_Common_Room_AvailableFieldSpecified;
            }
            set {
                this.boys_Common_Room_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Boys_Common_Room_Details {
            get {
                return this.boys_Common_Room_DetailsField;
            }
            set {
                this.boys_Common_Room_DetailsField = value;
            }
        }
        
        /// <remarks/>
        public Roof_Top_Solar_Panel_Available Roof_Top_Solar_Panel_Available {
            get {
                return this.roof_Top_Solar_Panel_AvailableField;
            }
            set {
                this.roof_Top_Solar_Panel_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Roof_Top_Solar_Panel_AvailableSpecified {
            get {
                return this.roof_Top_Solar_Panel_AvailableFieldSpecified;
            }
            set {
                this.roof_Top_Solar_Panel_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Rain_Water_Harvesting_Avail Rain_Water_Harvesting_Avail {
            get {
                return this.rain_Water_Harvesting_AvailField;
            }
            set {
                this.rain_Water_Harvesting_AvailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Rain_Water_Harvesting_AvailSpecified {
            get {
                return this.rain_Water_Harvesting_AvailFieldSpecified;
            }
            set {
                this.rain_Water_Harvesting_AvailFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Sewage_Treatment_Plant_Avail Sewage_Treatment_Plant_Avail {
            get {
                return this.sewage_Treatment_Plant_AvailField;
            }
            set {
                this.sewage_Treatment_Plant_AvailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Sewage_Treatment_Plant_AvailSpecified {
            get {
                return this.sewage_Treatment_Plant_AvailFieldSpecified;
            }
            set {
                this.sewage_Treatment_Plant_AvailFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Internet_Connection_Available Internet_Connection_Available {
            get {
                return this.internet_Connection_AvailableField;
            }
            set {
                this.internet_Connection_AvailableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Internet_Connection_AvailableSpecified {
            get {
                return this.internet_Connection_AvailableFieldSpecified;
            }
            set {
                this.internet_Connection_AvailableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Uploaded_FileName {
            get {
                return this.uploaded_FileNameField;
            }
            set {
                this.uploaded_FileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Field_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Sport’s_Court_Available", Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Sports_Court_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Field_Gallery_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Conference_Room_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Video_Conference_Room_Avail {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Library_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Central_Library_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Digital_Library_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Canteen_Caf_for_Staffs_Avail {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Dispensary_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum CoE_Program_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum CSR_Activities_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Staff_Common_Room_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Girls_Common_Room_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Boys_Common_Room_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Roof_Top_Solar_Panel_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Rain_Water_Harvesting_Avail {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Sewage_Treatment_Plant_Avail {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum Internet_Connection_Available {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public partial class GeneralLandBuildingCard_Filter {
        
        private GeneralLandBuildingCard_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public GeneralLandBuildingCard_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/generallandbuildingcard")]
    public enum GeneralLandBuildingCard_Fields {
        
        /// <remarks/>
        Year_of_Establis_of_institute,
        
        /// <remarks/>
        Field_Available,
        
        /// <remarks/>
        Field_Area_in_Acres,
        
        /// <remarks/>
        Sport_x2019_s_Court_Available,
        
        /// <remarks/>
        Sports_Court_Area_in_Sqft,
        
        /// <remarks/>
        Field_Gallery_Available,
        
        /// <remarks/>
        Conference_Room_Available,
        
        /// <remarks/>
        Video_Conference_Room_Avail,
        
        /// <remarks/>
        Floor_size_of_the_Video_conf,
        
        /// <remarks/>
        Video_Conference_Room_Location,
        
        /// <remarks/>
        Video_Conference_Room_Capacity,
        
        /// <remarks/>
        Library_Available,
        
        /// <remarks/>
        Central_Library_Available,
        
        /// <remarks/>
        Digital_Library_Available,
        
        /// <remarks/>
        Canteen_Caf_for_Staffs_Avail,
        
        /// <remarks/>
        Canteen_Cafeteria_Capacity,
        
        /// <remarks/>
        Dispensary_Available,
        
        /// <remarks/>
        CoE_Program_Available,
        
        /// <remarks/>
        CoE_Program_Details,
        
        /// <remarks/>
        CSR_Activities_Available,
        
        /// <remarks/>
        CSR_Activity_Details,
        
        /// <remarks/>
        Staff_Common_Room_Available,
        
        /// <remarks/>
        Staff_Common_Room_Details,
        
        /// <remarks/>
        Girls_Common_Room_Available,
        
        /// <remarks/>
        Girls_Common_Room_Details,
        
        /// <remarks/>
        Boys_Common_Room_Available,
        
        /// <remarks/>
        Boys_Common_Room_Details,
        
        /// <remarks/>
        Roof_Top_Solar_Panel_Available,
        
        /// <remarks/>
        Rain_Water_Harvesting_Avail,
        
        /// <remarks/>
        Sewage_Treatment_Plant_Avail,
        
        /// <remarks/>
        Internet_Connection_Available,
        
        /// <remarks/>
        Uploaded_FileName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralLandBuildingCard Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralLandBuildingCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralLandBuildingCard[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralLandBuildingCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralLandBuildingCard GeneralLandBuildingCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralLandBuildingCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralLandBuildingCard[] GeneralLandBuildingCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralLandBuildingCard[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralLandBuildingCard GeneralLandBuildingCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralLandBuildingCard)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralLandBuildingCard[] GeneralLandBuildingCard_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralLandBuildingCard[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591